# Generated by Django 3.1.1 on 2020-09-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoID', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('published', models.DateTimeField()),
                ('description', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('thumbUrls', models.CharField(blank=True, default=None, max_length=120, null=True)),
            ],
        ),
    ]
